### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by Ypy12310** [Dpw506/TLCKD-Net#1]
Hello, when I run your code I get the following error: 'ModuleNotFoundError: No module named 'model.rest'' Please can you tell me how to get the rest file

**Comment by Dpw506** [comment]
A million apologies for overlooking this, I have updated my own code, please check it out.

**Comment by Ypy12310** [comment]
Thank you very much for your reply

**Comment by 1pengliu** [comment]
> 千百个抱歉忽略了这一点，我已经更新了自己的代码，请查看。

请问Windows系统能跑此项目吗

**Comment by Dpw506** [comment]
> > 千百个抱歉忽略了这一点，我已经更新了自己的代码，请查看。
> 
> 请问Windows系统能跑此项目吗

可以的

**Comment by 1pengliu** [comment]
> > > 千百个抱歉忽略了这一点，我已经更新了自己的代码，请查看。
> > 
> > 
> > 请问Windows系统能跑此项目吗
> 
> 可以的

您好可以问一下ORSSD数据集里面的压缩包的解压密码吗，发邮件询问原作者一直没有回复

**Comment by Dpw506** [comment]
> > > > 千百个抱歉忽略了这一点，我已经更新了自己的代码，请查看。
> > > 
> > > 
> > > 请问Windows系统能跑此项目吗
> > 
> > 
> > 可以的
> 
> 您好可以问一下ORSSD数据集里面的压缩包的解压密码吗，发邮件询问原作者一直没有回复

你是需要orssd数据集吗？

**Comment by 1pengliu** [comment]
> > > > > 千百个抱歉忽略了这一点，我已经更新了自己的代码，请查看。
> > > > 
> > > > 
> > > > 请问Windows系统能跑此项目吗
> > > 
> > > 
> > > 可以的
> > 
> > 
> > 您好可以问一下ORSSD数据集里面的压缩包的解压密码吗，发邮件询问原作者一直没有回复
> 
> 你是需要orssd数据集吗？

对，网上找的这个数据集下载之后里面的压缩包解压需要密码

**Comment by Dpw506** [comment]
> > > > > > 千百个抱歉忽略了这一点，我已经更新了自己的代码，请查看。
> > > > > 
> > > > > 
> > > > > 请问Windows系统能跑此项目吗
> > > > 
> > > > 
> > > > 可以的
> > > 
> > > 
> > > 您好可以问一下ORSSD数据集里面的压缩包的解压密码吗，发邮件询问原作者一直没有回复
> > 
> > 
> > 你是需要orssd数据集吗？
> 
> 对，网上找的这个数据集下载之后里面的压缩包解压需要密码
我可以提供给你数据集：
EORSSD:   https://pan.baidu.com/s/1HMcsilJSavIXYf1vAhFZ2Q 提取码: 2024 
ORSSD: https://pan.baidu.com/s/10H-X2Zi5Ij_TqdZ34DCizQ 提取码: 2024

**Comment by 1pengliu** [comment]
> > > > > > > 千百个抱歉忽略了这一点，我已经更新了自己的代码，请查看。
> > > > > > 
> > > > > > 
> > > > > > 请问Windows系统能跑此项目吗
> > > > > 
> > > > > 
> > > > > 可以的
> > > > 
> > > > 
> > > > 您好可以问一下ORSSD数据集里面的压缩包的解压密码吗，发邮件询问原作者一直没有回复
> > > 
> > > 
> > > 你是需要orssd数据集吗？
> > 
> > 
> > 对，网上找的这个数据集下载之后里面的压缩包解压需要密码 我可以提供给你数据集： EORSSD： https://pan.baidu.com/s/1HMcsilJSavIXYf1vAhFZ2Q 提取码： 2024 ORSSD： https://pan.baidu.com/s/10H-X2Zi5Ij_TqdZ34DCizQ 提取码： 2024

感谢分享！
